<?php
/**
 * @var $this Mage_Catalog_Block_Product_View;
 */
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>

<?php
/** @var $_product Mage_Catalog_Model_Product  */
$_product = $this->getProduct();
?>
<?php
/** @var $_wishlistSubmitUrl Mage_Core_Block_Template  */
$_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product);
?>

<div class="add-to-links">
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_wishlistSubmitUrl ?>'); return false;" class="label label-info"><?php echo $this->__('Add to Wishlist') ?></a>
<?php endif; ?>
<?php
 /** @var $_compareUrl Mage_Core_Block_Template */
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);

?>
<?php if($_compareUrl) : ?>
    <span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="label label-info"><?php echo $this->__('Add to Compare') ?></a>
<?php endif; ?>
</div>
